== SQL Command Mode

`SQL CMD Mode` adds simple macros to the development environment.  It is also available from the command line; see <<SQLCMD>> .

Start SQL Command Mode by choosing `Query | SQL CMD Mode`.

=== Reuse Parameters

The scope of the `DECLARE` statement is one code block:

[source,tsql]
----
-- ensure that DECLARE in earlier section of code matches these values
DECLARE @STARTING_DATE DATE = '09/01/15';
DECLARE @ENDING_DATE DATE = '09/30/15';

-- perform the first query, using the specified date range, producing the first result set
SELECT  *
FROM    TABLE_0
WHERE   STARTING_DATE >= @STARTING_DATE AND ENDING_DATE <= @ENDING_DATE
GO

-- ensure that DECLARE in earlier section of code matches these values
DECLARE @STARTING_DATE DATE = '09/01/15';
DECLARE @ENDING_DATE DATE = '09/30/15';

-- perform a second query, using the same date range, producing the second result set
SELECT  *
FROM    TABLE_1
WHERE   STARTING_DATE >= @STARTING_DATE AND ENDING_DATE <= @ENDING_DATE
GO
----

In SQL Command Mode, variables can be reused:

[source,tsql]
----
:setvar starting_date '09/01/15'
:setvar ending_date '09/30/15'

-- perform the first query, using the specified date range, producing the first result set
SELECT  *
FROM    TABLE_0
WHERE   STARTING_DATE >= $(starting_date) AND ENDING_DATE <= $(ending_date)
GO

-- perform a second query, using the same date range, producing the second result set
SELECT  *
FROM    TABLE_1
WHERE   STARTING_DATE >= $(starting_date) AND ENDING_DATE <= $(ending_date)
GO
----

=== Automatic exports

Automatically export a result set as a CSV file.

[source,tsql]
----
-- disable counts; '(x row(s) affected)' message that is echoed to file
SET NOCOUNT ON
GO

-- define a base path that can be repeatedly referenced, if necessary
:setvar path c:\path\to\directory\

-- perform a query, saving the results to a CSV file
:Out $(path)TABLE_0.csv
SELECT  *
FROM    TABLE_0
GO

-- restore counts
SET NOCOUNT OFF
GO
----

== Gotchas

=== Exporting CSV Files

==== Null Values

When exporting a query's results to a CSV file, SSMS 2012 substitutes the word 'NULL' for `NULL` values.

[source,sql]
----
SELECT  'LOREM IPSUM' TEXT_FIELD_0
        ,NULL NULL_FIELD
        ,'LOREM IPSUM' TEXT_FIELD_1
----

Desired:

[source,csv]
----
TEXT_FIELD_0,NULL_FIELD,TEXT_FIELD_1
LOREM IPSUM,,LOREM IPSUM
----

Actual:

[source,csv]
----
TEXT_FIELD_0,NULL_FIELD,TEXT_FIELD_1
LOREM IPSUM,NULL,LOREM IPSUM
----

===== Solution

Post-process the file to remove the word 'NULL'.

==== Date/Time Values

When `DATETIME` values are exported as CSV, milliseconds are included.  By default, Excel will format this data as a time value, potentially leading to confusion.

[source,sql]
----
SELECT  GetDate() MILLISECONDS
----

[source,csv]
----
MILLISECONDS
2015-09-25 10:57:53.740
----

===== Solution

`CONVERT` the field to `ODBC Canonical` format.  Use the <<Milliseconds>> snippet.
[source,sql]
----
SELECT  CONVERT(VARCHAR, GetDate(), 120) NO_MILLISECONDS
----

[source,csv]
----
NO_MILLISECONDS
2015-09-25 10:57:53
----

==== :Out Command

When using the `:out` macro in <<SQL Command Mode>> , textual values aren't automatically escaped with double quotes.  If the text contains a comma, it will be seen as a delimiter, leading to errorenous parsing.

[source,sql]
----
SELECT  'STRING, WITH A COMMA' FIELD_WITH_A_COMMA
----

[source,csv]
----
FIELD_WITH_A_COMMA
STRING, WITH A COMMA
----

===== Solution

Use the `QuoteName` function to wrap the field in double quotes,

[source,sql]
----
SELECT  QuoteName('STRING, WITH A COMMA', Char(34)) FIELD_WITH_A_COMMA
----

[source,csv]
----
FIELD_WITH_A_COMMA
"STRING, WITH A COMMA"
----
